version: '3.8'

services: 
  sqlserver:
    container_name: intaker-sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Admin123!"
    ports:
      - 1433:1433
    restart: always

  rabbitmq:
    container_name: intaker-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ default messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
